name: Run GDScript Tests

on:
  pull_request:
    paths:
      - '**.gd'  # Run tests if any GDScript file is modified
  push:
    branches:
      - main  # Run tests on pushes to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          mv Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot
      
      - name: Initialize Godot Project
        run: godot --headless --quit

      - name: Print directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "\nHome directory:"
          ls -la ~
          echo "\nWorkspace structure:"
          ls -la
          echo "\nFull project structure:"
          sudo apt-get update -y && sudo apt-get install -y tree
          tree -a -L 3
          echo "\nGUT addon verification:"
          ls -la src/addons/gut/cli/
        
      - name: Check project setup
        run: |
          echo "Checking for project.godot:"
          ls -la project.godot
          echo "\nChecking GUT CLI path:"
          ls -la src/addons/gut/cli/gut_cli.gd

      - name: Run GDScript Tests
        run: godot --headless --path ./ -s "res://addons/gut/cli/gut_cli.gd" -gdir="res://Tests"
