name: Run GDScript Tests

on:
  pull_request:
    paths:
      - '**.gd'  # Run tests if any GDScript file is modified
  push:
    branches:
      - main  # Run tests on pushes to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip
          unzip Godot_v4.3-stable_linux.x86_64.zip
          mv Godot_v4.3-stable_linux.x86_64 /usr/local/bin/godot
          chmod +x /usr/local/bin/godot

      - name: Cache Godot Imported Assets
        uses: actions/cache@v3
        with:
          path: src/.godot/imported
          key: godot-import-${{ github.run_id }}
          restore-keys: godot-import-

      - name: Force Asset Re-import
        working-directory: ./src
        run: |
          rm -rf .godot/imported
          godot --headless --editor --quit

      - name: Run GDScript Tests
        working-directory: ./src
        run: |
          godot --headless --import -s res://addons/gut/gut_cmdln.gd -ginclude_subdirs -gdir=res://Tests -gexit -gprefix=test_