name: Update Commit Numbers

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'

jobs:
  update-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}  # Checkout the selected branch

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run commit update script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python update_projMngmnt_tex.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/projMngmnt/Rev0_Team_Contrib.tex
          git commit -m "Update commit numbers"
          git push origin ${{ github.event.inputs.branch }}  # Push to the selected branch
